apiVersion: 1
datasources:
  - name: Postgres
    type: postgres
    access: proxy
    isDefault: true
    url: postgres:5432
    user: $POSTGRES_USER
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      database: $POSTGRES_DB
      sslmode: "disable"
      postgresVersion: 1500
      timescaledb: false